[package]
name = "bitcoin"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["lib", "miner", "node", "wallet"]

[dependencies]
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.140"
futures = "0.3.31"
